# $(@D) is an automatic variable meaning "the output directory" (a la GNU Make)
# All other paths are resolved relative to this directory containing this file

routes:
- path: content/ctp
  target: $(@D)/ctp.html
- path: content/pcph
  target: $(@D)/pcph.html
- path: css/buttondown.css
  target: buttondown.css

targets:
- path: $(@D)/ctp.html
  tool: pandoc
  dependencies:
  - ctp.md
- path: $(@D)/pcph.html
  tool: pandoc
  dependencies:
  - pcph.md

build-tool-settings:
  pandoc:
    template-path: template.html
    vars:
    - [css, css/buttondown.css]

first-name: Richard
last-name: Cook
