routes:
- path: content/ctp
  target: ctp.html
- path: content/pcph
  target: pcph.html

targets:
- path: ctp.html
  tool: pandoc
  dependencies:
  - ctp.md
- path: pcph.html
  tool: pandoc
  dependencies:
  - pcph.md

build-tool-settings:
  pandoc:
    template-path: template.html
    vars:
    - [css, css/buttondown.css]

first-name: Richard
last-name: Cook
